#ifndef __DRV_ADC_H__
#define __DRV_ADC_H__
#include "gd32f10x.h"

#define 	AD_TEMP_PIN							GPIO_PIN_1
#define 	AD_TEMP_GPIO_PORT				GPIOA
#define 	AD_TEMP_GPIO_CLK				RCC_APB2PERIPH_GPIOA

#define 	AD_VOL_48V_PIN					GPIO_PIN_2
#define 	AD_VOL_48V_GPIO_PORT		GPIOA
#define 	AD_VOL_48V_GPIO_CLK			RCC_APB2PERIPH_GPIOA

#define 	AD_CUR_48V_PIN					GPIO_PIN_0
#define 	AD_CUR_48V_GPIO_PORT		GPIOC
#define 	AD_CUR_48V_GPIO_CLK			RCC_APB2PERIPH_GPIOC

#define 	AD_VOL_28V_PIN					GPIO_PIN_4
#define 	AD_VOL_28V_GPIO_PORT		GPIOA
#define 	AD_VOL_28V_GPIO_CLK			RCC_APB2PERIPH_GPIOA

#define 	AD_CUR_28V_PIN					GPIO_PIN_5
#define 	AD_CUR_28V_GPIO_PORT		GPIOA
#define 	AD_CUR_28V_GPIO_CLK			RCC_APB2PERIPH_GPIOA

#define 	AD_VOL_24V_PIN					GPIO_PIN_6
#define 	AD_VOL_24V_GPIO_PORT		GPIOA
#define 	AD_VOL_24V_GPIO_CLK			RCC_APB2PERIPH_GPIOA

#define 	AD_CUR_24V_PIN					GPIO_PIN_7
#define 	AD_CUR_24V_GPIO_PORT		GPIOA
#define 	AD_CUR_24V_GPIO_CLK			RCC_APB2PERIPH_GPIOA

#define 	AD_VOL_12V_PIN					GPIO_PIN_0
#define 	AD_VOL_12V_GPIO_PORT		GPIOB
#define 	AD_VOL_12V_GPIO_CLK			RCC_APB2PERIPH_GPIOB

#define 	AD_CUR_12V_PIN					GPIO_PIN_1
#define 	AD_CUR_12V_GPIO_PORT		GPIOB
#define 	AD_CUR_12V_GPIO_CLK			RCC_APB2PERIPH_GPIOB

#define 	AD_VOL_5V5_PIN					GPIO_PIN_4
#define 	AD_VOL_5V5_GPIO_PORT		GPIOC
#define 	AD_VOL_5V5_GPIO_CLK			RCC_APB2PERIPH_GPIOC

#define 	AD_CUR_5V5_PIN					GPIO_PIN_5
#define 	AD_CUR_5V5_GPIO_PORT		GPIOC
#define 	AD_CUR_5V5_GPIO_CLK			RCC_APB2PERIPH_GPIOC


#define 	AD_CHANNEL 					11
#define		TIMES								10

extern void DRV_ADC_Init(void);

#endif

